### ISSUE TITLE
Remote host does not work

### ISSUE THREAD

**Issue by b9sk** [b9sk/docker-drupal-dev#2]
todo: create another service inside docker-compose.yml with DBGp proxy (see old commits)

**Comment by b9sk** [comment]
```
drupal-dev_1  | INFO: dbgp.proxy: Server:onConnect ('172.18.0.1', 52866) [proxyinit -p 9000 -k mySecretKey666 -m 1]
drupal-dev_1  | 172.18.0.1 - - [27/Nov/2018:10:38:15 +0000] "GET / HTTP/1.1" 200 278 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.77 Chrome/70.0.3538.77 Safari/537.36"
drupal-dev_1  | 172.18.0.1 - - [27/Nov/2018:10:38:15 +0000] "GET /favicon.ico HTTP/1.1" 404 501 "http://0.0.0.0:30080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.77 Chrome/70.0.3538.77 Safari/537.36"
drupal-dev_1  | INFO: dbgp.proxy: connection from 127.0.0.1:50330 [<__main__.sessionProxy instance at 0x7fb5f370c128>]
drupal-dev_1  | ERROR: dbgp.proxy: Unable to connect to the server listener 172.18.0.1:9000 [<__main__.sessionProxy instance at 0x7fb5f370c128>]
drupal-dev_1  | Traceback (most recent call last):
drupal-dev_1  |   File "/usr/local/bin/pydbgpproxy", line 220, in startServer
drupal-dev_1  |     self._server.connect((self._serverAddr[0], self._serverAddr[1]))
drupal-dev_1  |   File "/usr/lib/python2.7/socket.py", line 228, in meth
drupal-dev_1  |     return getattr(self._sock,name)(*args)
drupal-dev_1  | error: [Errno 111] Connection refused
```
**`drupal-dev_1  | WARNING: dbgp.proxy: Unable to connect to server with key [mySecretKey666], stopping request [<__main__.sessionProxy instance at 0x7fb5f370c128>]`**
```
drupal-dev_1  | INFO: dbgp.proxy: session stopped
drupal-dev_1  | There was a problem sending 178 bytes on socket 12: Connection reset by peerThere was a problem sending 264 bytes on socket 12: Broken pipe172.18.0.1 - - [27/Nov/2018:10:38:31 +0000] "GET / HTTP/1.1" 200 278 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.77 Chrome/70.0.3538.77 Safari/537.36"
```
